services:
  api:
    build: ./tasks-api
    ports:
      - "3000:3000"
    volumes:
      - ./tasks-api:/app:cached
      - api_gems:/usr/local/bundle
    environment:
      - RAILS_ENV=test
    command: sh -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"

  frontend:
    build: ./task-manager-ui
    ports:
      - "5173:5173"
    volumes:
      - ./task-manager-ui:/app
      - /app/node_modules
volumes:
  api_gems:
